### ISSUE TITLE
Prediction discrepancies between Python's coremltools and Swift's CoreML API

### ISSUE THREAD

**Issue by alwc** [hollance/CoreMLHelpers#38]
Hi @hollance, is it possible to get the exact numbers from Python's `coremltools` results in Swift?

That is, When I'm using `coremltools` (Python), I have the following code:

```{python}
spec = coremltools.utils.load_spec('./alwc_model.mlmodel')
mlmodel = coremltools.models.MLModel(spec)
input_img = Image.open("input_image.jpg") // width 512, height 512, mode RGB 
prediction = mlmodel.predict({"input_image": input_img}, usesCPUOnly=True)
output = prediction["output"]
```

In the Xcode project, I have the following code:

```{swift}
let inputImage = #imageLiteral(resourceName: "input_image.jpg")

guard let imageBuffer = inputImage.pixelBuffer(width: 512, height: 512) else {
    let options = MLPredictionOptions()
    options.usesCPUOnly = true
    let model = alwc_model()
    let input = alwc_modelInput(input_image: imageBuffer)
    let prediction = try! model.prediction(input: input, options: options)
    let output = prediction.output
}
```

Note that I'm using https://github.com/hollance/CoreMLHelpers/blob/0bd7f983c3e73abcffb692b4428e889ed4cf01b6/CoreMLHelpers/UIImage%2BCVPixelBuffer.swift to convert the `UIImage` into `CVPixelBuffer` and I'm running on a simulator.

My concern is that while the output is fairly close (off by ~0.02), I'm surprised they are not exactly the same since I believe both of them should be using the macOS's Core ML framework right?

I suspect it could be because of the image conversion step. For example, I found that in `coremltools` (ref: https://github.com/apple/coremltools/blob/master/coremlpython/CoreMLPythonUtils.mm#L204) its `pixelFormatType` is `kCVPixelFormatType_32BGRA` while yours is `kCVPixelFormatType_32ARGB`. I tried to use `kCVPixelFormatType_32BGRA` for the `pixelBuffer` method, but the output in the Xcode project is still not the same as the one from Python. 

Do you have experience trying to match the results between Python's coremltools and Swift's CoreML API? Thanks!

**Comment by hollance** [comment]
Try it with a PNG image. There may be differences in how the JPEG image is loaded in Python vs macOS.

**Comment by alwc** [comment]
> Try it with a PNG image. There may be differences in how the JPEG image is loaded in Python vs macOS.

Thanks for your suggestion. Using PNG image the output difference between `coremltools` and the Xcode project is now down to ~0.001. 

While the diff is close enough. Is that normal? Shouldn't we expect the two outputs to be identical in this case?

**Comment by hollance** [comment]
I would expect to see 0.001 differences if one is using the GPU while the other is using the CPU. I think if both are using the CPU on the same device, the difference should be smaller. But it might depend on what exactly happens inside the model.

You could try using Vision in the app, which allows you to pass in a CGImage directly without having to convert it to a CVPixelBuffer yourself.

Usually when I want to make 100% sure the model does the correct thing, I remove all the layers and verify that the output after preprocessing is the same in both cases. You can find something similar here (although you'd want to change the output's type to MultiArray instead of image): https://github.com/hollance/coreml-survival-guide/tree/master/CheckInputImage

**Comment by alwc** [comment]
Thanks for your suggestion. I'll check out the project and take a look of the section "Making Sure the Input is Correct" in your book.
